In [1]:
import numpy as np

In [2]:
matrix_a = np.arange(9, dtype=float).reshape(3,3)
matrix_a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [3]:
array_b= np.array([10,10,10])
array_b

array([10, 10, 10])

In [4]:
np.add(matrix_a, array_b)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [5]:
np.subtract(matrix_a, array_b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [6]:
np.multiply(matrix_a, array_b)

array([[ 0., 10., 20.],
       [30., 40., 50.],
       [60., 70., 80.]])

In [7]:
np.divide(matrix_a, array_b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])